apiVersion: v1
kind: Service
metadata:
  name: node-hello-service
spec:
  selector:
    # Must match the labels in the deployment
    app: node-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer